name: Release
on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Tag name for release"
        required: false
        default: nightly
  push:
    branches:
      - main

# Build on the oldest supported images, so we have broader compatibility
# Build with gcc-10 to prevent triggering #14150 (default is still gcc-9 on 20.04)
jobs:
  linux:
    runs-on: ubuntu-20.04
    outputs:
      version: ${{ steps.build.outputs.version }}
      release: ${{ steps.build.outputs.release }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake build-essential cmake gettext libtool-bin locales ninja-build pkg-config unzip
      - if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.tag_name != 'nightly')
        run: printf 'NVIM_BUILD_TYPE=Release\n' >> $GITHUB_ENV
      - if: github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && github.event.inputs.tag_name == 'nightly')
        run: printf 'NVIM_BUILD_TYPE=RelWithDebInfo\n' >> $GITHUB_ENV
      - name: Build release
        id: build
        run: |
          CC=gcc-10 make CMAKE_BUILD_TYPE=${NVIM_BUILD_TYPE} CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX:PATH="
          printf '::set-output name=version::%s\n' "$(./build/bin/nvim --version | head -n 3 | sed -z 's/\n/%0A/g')"
          printf '::set-output name=release::%s\n' "$(./build/bin/nvim --version | head -n 1)"
          make DESTDIR="$GITHUB_WORKSPACE/build/release/nvim-linux64" install
          cd "$GITHUB_WORKSPACE/build/"
          cpack -C $NVIM_BUILD_TYPE
      - uses: actions/upload-artifact@v3
        with:
          name: nvim-linux64
          path: build/nvim-linux64.tar.gz
          retention-days: 1

      - uses: actions/upload-artifact@v3
        with:
          name: nvim-linux64
          path: build/nvim-linux64.deb
          retention-days: 1

  macOS:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install brew packages
        run: |
          brew update --quiet
          brew install automake ninja
      - if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.tag_name != 'nightly')
        run: printf 'NVIM_BUILD_TYPE=Release\n' >> $GITHUB_ENV
      - if: github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && github.event.inputs.tag_name == 'nightly')
        run: printf 'NVIM_BUILD_TYPE=RelWithDebInfo\n' >> $GITHUB_ENV
      - name: Provision universal `libintl`
        run: |
          GETTEXT_PREFIX="$(brew --prefix gettext)"
          printf 'GETTEXT_PREFIX=%s\n' "$GETTEXT_PREFIX" >> $GITHUB_ENV
          bottle_tag="arm64_big_sur"
          brew fetch --bottle-tag="$bottle_tag" gettext
          cd "$(mktemp -d)"
          tar xf "$(brew --cache)"/**/*gettext*${bottle_tag}*.tar.gz
          lipo gettext/*/lib/libintl.a "${GETTEXT_PREFIX}/lib/libintl.a" -create -output libintl.a
          mv -f libintl.a /usr/local/lib/
      - name: Ensure static linkage to `libintl`
        run: |
          # We're about to mangle `gettext`, so let's remove any potentially broken
          # installs (e.g. curl, git) as those could interfere with our build.
          brew uninstall $(brew uses --installed --recursive gettext)
          brew unlink gettext
          ln -sf "$(brew --prefix)/opt/$(readlink "${GETTEXT_PREFIX}")/bin"/* /usr/local/bin/
          ln -sf "$(brew --prefix)/opt/$(readlink "${GETTEXT_PREFIX}")/include"/* /usr/local/include/
          rm -f "$GETTEXT_PREFIX"
      - name: Build release
        run: |
          export MACOSX_DEPLOYMENT_TARGET="$(sw_vers -productVersion | cut -f1 -d.)"
          OSX_FLAGS="-DCMAKE_OSX_DEPLOYMENT_TARGET=${MACOSX_DEPLOYMENT_TARGET} -DCMAKE_OSX_ARCHITECTURES=arm64\;x86_64"
          make CMAKE_BUILD_TYPE=${NVIM_BUILD_TYPE} \
               CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX:PATH= $OSX_FLAGS" \
               DEPS_CMAKE_FLAGS="$OSX_FLAGS"
          make DESTDIR="$GITHUB_WORKSPACE/build/release/nvim-macos" install
          cd "$GITHUB_WORKSPACE/build/"
          cpack -C "$NVIM_BUILD_TYPE"
      - uses: actions/upload-artifact@v3
        with:
          name: nvim-macos
          path: build/nvim-macos.tar.gz
          retention-days: 1

  publish:
    needs: [linux, macOS]
    runs-on: macos-latest
    env:
      GH_REPO: ${{ github.repository }}
    permissions:
      contents: write
    steps:
      # Must perform checkout first, since it deletes the target directory
      # before running, and would therefore delete the downloaded artifacts
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3

      - name: Install dependencies
        run: |
          brew update
          brew install gh gettext

      # `sha256sum` outputs <sha> <path>, so we cd into each dir to drop the
      # containing folder from the output.
      - name: Generate Linux64 SHA256 checksums
        run: |
          cd ./nvim-linux64
          shasum -a 256 nvim-linux64.tar.gz > nvim-linux64.tar.gz.sha256sum
          echo "SHA_LINUX_64_TAR=$(cat nvim-linux64.tar.gz.sha256sum)" >> $GITHUB_ENV
          shasum -a 256 nvim-linux64.deb > nvim-linux64.deb.sha256sum
          echo "SHA_LINUX_64_DEB=$(cat nvim-linux64.deb.sha256sum)" >> $GITHUB_ENV
      - name: Generate macOS SHA256 checksums
        run: |
          cd ./nvim-macos
          shasum -a 256 nvim-macos.tar.gz > nvim-macos.tar.gz.sha256sum
          echo "SHA_MACOS=$(cat nvim-macos.tar.gz.sha256sum)" >> $GITHUB_ENV
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          (echo 'SUBJECT=Nvim development (prerelease) build';
           echo 'PRERELEASE=--prerelease') >> $GITHUB_ENV
          gh release delete nightly --yes || true
          git push origin :nightly || true
      - name: Publish release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NVIM_VERSION: ${{ needs.linux.outputs.version }}
          DEBUG: api
        run: |
          envsubst < "$GITHUB_WORKSPACE/.github/workflows/notes.md" > "$RUNNER_TEMP/notes.md"
          gh release create nightly $PRERELEASE --notes-file "$RUNNER_TEMP/notes.md" --title "$SUBJECT" --target $GITHUB_SHA nvim-macos/* nvim-linux64/*
          gh release edit nightly --draft=false
